# .github/workflows/lint-and-test.yml
name: Lint & Test

on:
  push:
    paths:
      - 'main.sh'
      - 'scripts/**/*.sh'
  pull_request:
    paths:
      - 'main.sh'
      - 'scripts/**/*.sh'

jobs:
  # 1. Lint with ShellCheck
  shellcheck:
    name: ShellCheck Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: .
          ignore_paths: |
            .git
            .github

  # 2. Format-check with shfmt
  shfmt:
    name: shfmt Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run shfmt
        uses: shfmt-dev/action-shfmt@v3
        with:
          args: -d main.sh scripts

  # 3. Smoke-test installers with Bats
  bats:
    name: BATS Smoke Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # install Bats for shell unit tests
      - name: Install Bats
        run: |
          sudo apt-get update
          sudo apt-get install -y bats

      # run any .bats tests you create under tests/
      - name: Run BATS tests
        run: |
          if [ -d tests ]; then
            bats --tap tests | tee bats-output.tap
            grep -q "^not ok" bats-output.tap && exit 1 || true
          else
            echo "⚠️  no tests/ directory found, skipping BATS"
          fi

      # ensure your main.sh at least shows help without error
      - name: Smoke-test main.sh --help
        run: bash main.sh help
